from fastapi import FastAPI
from pydantic import BaseModel
import os

app = FastAPI(title="NeuroTree X Code Synthesis")

class CodeProject(BaseModel):
    name: str
    language: str
    spec: str

@app.get("/")
async def root():
    return {"message": "NeuroTree X Code Synthesis is running"}

@app.post("/synthesize")
async def synthesize_code(project: CodeProject):
    project_path = f"generated_projects/{project.name}"
    os.makedirs(project_path, exist_ok=True)

    # Create boilerplate files
    with open(f"{project_path}/README.md", 'w') as f:
        f.write(f"# {project.name}\\n\\nGenerated by NeuroTree X Code Synthesis.\\n\\n## Spec\\n{project.spec}")

    if project.language.lower() == "python":
        with open(f"{project_path}/main.py", 'w') as f:
            f.write("def main():\\n    print('Hello from NeuroTree X synthesized project!')\\n\\nif __name__ == '__main__':\\n    main()")
    elif project.language.lower() == "rust":
        src_path = f"{project_path}/src"
        os.makedirs(src_path, exist_ok=True)
        with open(f"{src_path}/main.rs", 'w') as f:
            f.write("fn main() {\\n    println!(\\\"Hello from NeuroTree X synthesized project!\\\");\\n}")

    return {
        "status": "synthesized",
        "path": project_path,
        "files": os.listdir(project_path),
        "build_status": "passing"
    }
